version: 2
jobs:
  build:
    docker:
      - image: admesg/pism-debian:0.1.5
        environment:
          PETSC_DIR: /usr/lib/petscdir/petsc3.10/x86_64-linux-gnu-real
          OMPI_MCA_rmaps_base_oversubscribe: yes
          OMPI_MCA_btl: "^vader"
          CTEST_OUTPUT_ON_FAILURE: 1

    steps:
      - checkout

      - run:
          name: Build PISM
          command: >-
            mkdir -p build &&
            cd build &&
            CC=mpicc CXX=mpicxx
            cmake ..
            -DCMAKE_BUILD_TYPE=Debug
            -DCMAKE_CXX_FLAGS=-Wno-cast-function-type
            -DPism_BUILD_PYTHON_BINDINGS=Yes
            -DPism_BUILD_EXTRA_EXECS=Yes
            -DPism_USE_PROJ=Yes &&
            make

      - run:
          name: Run PISM test suite
          command: >-
            cd build &&
            export PYTHONPATH=$PWD/site-packages:$PYTHONPATH &&
            make test
